name: Bug Report
description: Help us reproduce the problem!
labels: ["bug"]

body:

  - type: checkboxes
    id: about-the-bug
    attributes:
      label: About the Bug...
      description: Plesae check a few things before start writing the report.
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have confirmed this bug exists on the
            [latest version](https://github.com/mybatis/mybatis-3/releases/latest) of MyBatis.
          required: true
        - label: >
            I have confirmed this bug reproduces without 3rd party extensions (e.g. mybatis-plus).
          required: true

  - type: input
    id: db-version
    attributes:
      label: Database Version
      description: Which DB did you use to verify the bug?
      placeholder: ex. MySQL 8.0.43, PostgreSQL 17.5
    validations:
      required: true

  - type: input
    id: driver-version
    attributes:
      label: JDBC Driver Version
      description: We will try to use the same driver.
      placeholder: ex. MySQL Connector/J 9.3.0, PgJDBC 42.7.6
    validations:
      required: true

  - type: textarea
    id: issue-desc
    attributes:
      label: Issue Description
      description: |
        To fix the problem, we need to reproduce it first. ☝️
        - Provide as much detail as possible (config, DB data (DML, DDL), Java classes, Java/XML mappers, etc.).
        - Sharing a small executable demo project on your GitHub repository speeds up the process significantly 🏎️💨.  
        There are project templates and examples in this [repository](https://github.com/harawata/mybatis-issues).
        - If there is an exception, include the entire stack trace (the lower parts are important).

      value: |
        FYI, you can use GitHub Flavored Markdown here.

        ```sql
        CREATE TABLE users (id, name);
        INSERT INTO users (1, 'John');
        ```

        ```java
        @Select("select * from users")
        List<User> getAllUsers();
        ```
    validations:
      required: true

  - type: checkboxes
    id: about-your-report
    attributes:
      label: About your report...
      description: Please check a few things before submitting the report.
      options:
        - label: >
            I did not use images 🖼️ for showing text information (code, error, etc.).
          required: true
        - label: >
            I checked the Preview and my report looks awesome! 👍
          required: true
