blank_issues_enabled: false
contact_links:
  - name: Need Help?
    url: https://github.com/mybatis/mybatis-3/discussions
    about: Please post questions here.
  - name: Report Security Vulnerability
    url: https://github.com/mybatis/mybatis-3/security
    about: Please report security vulnerabilities here.
